# This is a basic workflow to help you get started with Actions

name: CI
env:
  http_proxy: http://proxy-prc.intel.com:913
  https_proxy: http://proxy-prc.intel.com:913
  no_proxy: intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
  DAY_OF_WEEK: Monday

# Controls when the workflow will run

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Job 2
        run: |
          echo "This is Job 2"
          echo "Current working directory: $PWD"
          ls
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image with Kaniko
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker run \
            -v $(pwd):/workspace \
            -v /var/run/docker.sock:/var/run/docker.sock \
            gcr.io/kaniko-project/executor:latest \
            --context /workspace \
            --dockerfile /workspace/Dockerfile \
            --destination ${{ github.repository_owner }}:latest \
            --tar-path ${{ github.repository_owner }}.tar \
            --no-push \

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.19.1/trivy_0.19.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.19.1_Linux-64bit.deb

      - name: Scan Docker Image with Trivy
        run: |
          trivy --severity HIGH,CRITICAL --format junit -o trivy_report.xml image --input ${{ github.repository_owner }}.tar

      - name: Generate Report
        uses: actions/upload-artifact@v3
        with:
          name: Trivy_Report
          path: trivy_report.xml

      - name: Show current folder
        run: |
          ls

      - name: Gzip Tar Archive
        run: |
          gzip ${{ github.repository_owner }}.tar
          ls -l
      # - name: Install BDBA
      #   run: |
      #     docker pull bestdoctor/bdba:latest

      - name: Scan Docker Image with BDBA
        run: |
          curl -k -H "Authorization: Bearer ${{secrets.BDBA_API_TOKEN}}" -H "Group: 32" -T ${{ github.repository_owner }}.tar.gz "https://bdba001.icloud.intel.com/api/upload/"

      - name: Show current folder
        run: |
          ls
          cd ${pwd}
          ls

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: step1
        run: |
          echo Hello, world!
          echo "::set-output name=test::hi"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: step2
        run: |
          env
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "::set-output name=test::world"
          echo "::debug::Set the Octocat variable"
          echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          # echo "::error file={name},line={line},endLine={endLine},title={title}::{message}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set triggering workflow name
        run: |
          echo "Hello, World!" 
          MY_VARIABLE="Hello, Jenny!"
          echo "Setting variable: $MY_VARIABLE"
          echo "MY_VARIABLE=$MY_VARIABLE" >> $GITHUB_ENV
          echo ${{needs.build.outputs.output1}} ${{needs.build.outputs.output2}}
          echo "action_state=yellow" >> "$GITHUB_ENV"
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: GET triggering workflow name
        run: |
          echo "Hello, World!"  > out.txt
          printf '%s\n' "$action_state"
          echo ${{ env.DAY_OF_WEEK }}
          echo $GITHUB_WORKFLOW is completed with the status ${{ github.action_status }}
          echo ${{ job.status }} ${{ github.event.issue.html_url }} jobs.test.result ${{ job.services.postgres.ports[5432] }}
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        shell: bash
      - name: Generate Report
        uses: actions/upload-artifact@v3
        with:
          name: HTML_Report
          path: out.txt
          retention-days: 5
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-weat-2
      - name: Sync files to S3 bucket
        run: |
          aws s3 cp out.txt s3://lc-mercury-integrationtest-logs/ --recursive
      - name: Output the result
        if: always()
        run: echo "Output the results"
