# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: step1
        run: |
          echo Hello, world!
          echo "::set-output name=test::hi"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: step2
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "::set-output name=test::world"
          echo "::debug::Set the Octocat variable"
          echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          # echo "::error file={name},line={line},endLine={endLine},title={title}::{message}

  test:
      runs-on: ubuntu-latest
      steps:
        - name: Set triggering workflow name
          run: |
             echo "Hello, World!" 
             MY_VARIABLE="Hello, Jenny!"
             echo "Setting variable: $MY_VARIABLE"
             echo "MY_VARIABLE=$MY_VARIABLE" >> $GITHUB_ENV
             echo ${{needs.build.outputs.output1}} ${{needs.build.outputs.output2}}
             echo "action_state=yellow" >> "$GITHUB_ENV"
  test2:
      runs-on: ubuntu-latest
      steps:
        - name: GET triggering workflow name
          run: |
             echo "Hello, World!" 
             printf '%s\n' "$action_state"
      
